<?php

declare(strict_types=1);

/**
 * Sitemap generator (Task 7.1).
 *
 *   php scripts/generate_sitemap.php            write public/sitemap.xml
 *   php scripts/generate_sitemap.php --stdout    print to stdout (no write)
 *
 * Emits a valid <urlset> (sitemaps.org 0.9) covering the public marketing /
 * commerce surfaces plus every PUBLISHED page and blog post from the `pages`
 * table. Private surfaces (admin, account, cart, checkout, auth, webhooks,
 * tokenized order/reservation links) are intentionally excluded — they are also
 * Disallowed in robots.txt.
 *
 * Base URL comes from config('url') (APP_URL). DB access goes through the
 * Database singleton with bound params; if the DB is unreachable (e.g. running
 * pre-provision), the script still emits the static routes and warns on stderr.
 */

$root = dirname(__DIR__);
require $root . '/includes/bootstrap.php';

use Amelias\Database\Database;

$toStdout = in_array('--stdout', $argv, true);

$baseUrl = rtrim((string) config('url', 'https://ameliasaz.com'), '/');

/**
 * Static public routes => change frequency / priority.
 * Mirrors the public GET routes in config/routes.php (no params, crawlable).
 */
$staticRoutes = [
    '/'              => ['weekly',  '1.0'],
    '/menu'          => ['weekly',  '0.9'],
    '/story'         => ['monthly', '0.7'],
    '/location'      => ['monthly', '0.7'],
    '/purveyors'     => ['monthly', '0.6'],
    '/careers'       => ['monthly', '0.5'],
    '/market'        => ['weekly',  '0.8'],
    '/gift-cards'    => ['monthly', '0.6'],
    '/wine-club'     => ['monthly', '0.7'],
    '/sunday-supper' => ['weekly',  '0.7'],
    '/catering'      => ['monthly', '0.7'],
    '/reserve'       => ['monthly', '0.8'],
    '/blog'          => ['weekly',  '0.6'],
    '/privacy'       => ['yearly',  '0.2'],
    '/terms'         => ['yearly',  '0.2'],
];

/** @var list<array{loc:string,lastmod:?string,changefreq:string,priority:string}> $urls */
$urls = [];
$now = gmdate('Y-m-d');

foreach ($staticRoutes as $path => [$freq, $priority]) {
    $urls[] = [
        'loc'        => $baseUrl . $path,
        'lastmod'    => $now,
        'changefreq' => $freq,
        'priority'   => $priority,
    ];
}

// Published CMS pages + blog posts. Posts route under /blog/{slug}; standalone
// pages render at /{slug}. Both come from the same `pages` table (0009_cms.sql).
$warning = null;
try {
    $rows = Database::fetchAll(
        'SELECT slug, type, updated_at, published_at
           FROM pages
          WHERE status = :status
          ORDER BY type, slug',
        ['status' => 'published']
    );
    foreach ($rows as $row) {
        $slug = trim((string) ($row['slug'] ?? ''));
        if ($slug === '') {
            continue;
        }
        $type = (string) ($row['type'] ?? 'page');
        $path = $type === 'post' ? '/blog/' . rawurlencode($slug) : '/' . rawurlencode($slug);

        // Skip a published page that would collide with a static route already listed.
        if (isset($staticRoutes[$path])) {
            continue;
        }

        $lastmod = $row['updated_at'] ?? $row['published_at'] ?? null;
        $urls[] = [
            'loc'        => $baseUrl . $path,
            'lastmod'    => $lastmod !== null ? gmdate('Y-m-d', strtotime((string) $lastmod)) : $now,
            'changefreq' => $type === 'post' ? 'monthly' : 'yearly',
            'priority'   => $type === 'post' ? '0.5' : '0.4',
        ];
    }
} catch (\Throwable $e) {
    // DB not reachable (e.g. pre-provision). Still emit static routes.
    $warning = 'Database unavailable — emitting static routes only: ' . $e->getMessage();
    fwrite(STDERR, "[generate_sitemap] WARNING: {$warning}\n");
}

// Build the XML with DOMDocument so escaping/validity is guaranteed.
$dom = new DOMDocument('1.0', 'UTF-8');
$dom->formatOutput = true;

$comment = $dom->createComment(
    ' Generated by scripts/generate_sitemap.php on ' . gmdate('c') . ' (UTC). Do not edit by hand. '
);
$dom->appendChild($comment);

$urlset = $dom->createElementNS('http://www.sitemaps.org/schemas/sitemap/0.9', 'urlset');
$dom->appendChild($urlset);

foreach ($urls as $u) {
    $urlEl = $dom->createElement('url');
    $urlEl->appendChild($dom->createElement('loc', htmlspecialchars($u['loc'], ENT_XML1)));
    if (!empty($u['lastmod'])) {
        $urlEl->appendChild($dom->createElement('lastmod', $u['lastmod']));
    }
    $urlEl->appendChild($dom->createElement('changefreq', $u['changefreq']));
    $urlEl->appendChild($dom->createElement('priority', $u['priority']));
    $urlset->appendChild($urlEl);
}

$xml = $dom->saveXML();
if ($xml === false) {
    fwrite(STDERR, "[generate_sitemap] ERROR: failed to serialize XML\n");
    exit(1);
}

if ($toStdout) {
    fwrite(STDOUT, $xml);
    exit(0);
}

$outFile = $root . '/public/sitemap.xml';
if (file_put_contents($outFile, $xml) === false) {
    fwrite(STDERR, "[generate_sitemap] ERROR: failed to write {$outFile}\n");
    exit(1);
}

fwrite(STDOUT, sprintf(
    "[generate_sitemap] wrote %s with %d URL(s)%s\n",
    'public/sitemap.xml',
    count($urls),
    $warning !== null ? ' (static only — DB unavailable)' : ''
));
exit(0);
